# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 79ccfce1a277666aaf691e9e513c57807528d504f786f7b1e673a1cd8c9cabf8c7745ef9fe17165734546b335e1415040e693c0584c94b0d4ca07bc8e55f982d

test:
  secret_key_base: f46d66983caf47317982a8e4b8e270738ee7353c2f9c183defb39988af7c5236dbcc049b4b056c6fd85ebefdf2f5467b13acec421b57694e149d95c33a0c0f6a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
